name: "Setup Node.js 22 with npm cache and Install dependencies"
description: "Installs Node.js 22 and sets up npm cache, then installs dependencies using npm ci"

inputs:
  run-npm-command:
    required: false
    description: "Whether to run npm ci to install dependencies. Set to 'true' to run, 'false' to skip."
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js 22 with npm cache
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: ${{ inputs.run-npm-command == 'true' && 'npm' || '' }}

    - name: Update npm
      if: ${{ inputs.run-npm-command == 'true' }}
      shell: bash
      run: npm install -g npm@latest

    - name: Install dependencies with npm ci
      if: ${{ inputs.run-npm-command == 'true' }}
      shell: bash
      run: npm ci --include=optional
