name: "Project to Markdown"
description: "Extract User Stories from a GitHub Project to a Markdown table"
inputs:
  token:
    required: true
    description: "GitHub App installation token"
  org:
    required: true
    description: "Organization name"
  project_number:
    required: true
    description: "Project number (not ID)"
  profile_label:
    required: true
    description: "Profile label to filter User Stories. Ex: 'Profil: Apprenant'"
  epic_label:
    required: true
    description: "Epic label to identify epics. Ex: 'Type: Epic'"
  out_file:
    required: true
    description: "Output Markdown file path"
runs:
  using: "composite"
  steps:
    - name: 🛠️ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📜 Generate Markdown table from Project
      shell: bash
      env:
        TOKEN:          ${{ inputs.token }}
        ORG:            ${{ inputs.org }}
        PROJECT_NUMBER: ${{ inputs.project_number }}
        PROFILE_LABEL:   ${{ inputs.profile_label }}
        EPIC_LABEL:     ${{ inputs.epic_label }}
        OUT_FILE:       ${{ inputs.out_file }}
      run: node "$GITHUB_ACTION_PATH/project-to-markdown.js"
