name: "Upload Templates"
description: "Upload necessary files for creating GitHub page and trivy report"
runs:
  using: "composite"
  steps:
    - name: 📥 Download GitHub Pages Template
      run: |
        curl -L https://github.com/avenirs-esr/avenirs-workflows/archive/refs/heads/feat/core-actions-workflows.tar.gz | tar -xz --strip=2 --wildcards --no-anchored 'gh-page-template/*' -C /tmp
      shell: bash

    - name: 📥 Download Trivy Template
      run: |
        curl -L https://github.com/avenirs-esr/avenirs-workflows/archive/refs/heads/feat/core-actions-workflows.tar.gz | tar -xz --strip=2 --wildcards --no-anchored 'trivy-template/*' -C /tmp
      shell: bash

    - name: 📦 Save Github Pages Template
      uses: actions/upload-artifact@v4
      with:
        name: gh-page-template
        path: /tmp/gh-page-template

    - name: 📦 Save Trivy Template
      uses: actions/upload-artifact@v4
      with:
        name: trivy-template
        path: /tmp/trivy-template
