name: "Upload Templates"
description: "Upload necessary files for creating GitHub page and trivy report"
runs:
  using: "composite"
  steps:
      - name: Clone reusable workflows and actions repository
        run: |
          git clone --single-branch --branch feat/core-actions-workflows --depth 1 https://github.com/avenirs-esr/avenirs-workflows.git /tmp/avenirs-workflows
        shell: bash
      - name: 📦 Save Github Pages Template
        uses: actions/upload-artifact@v4
        with:
          name: gh-page-template
          path: /tmp/avenirs-workflows/gh-page-template
      - name: 📦 Save Trivy Template
        uses: actions/upload-artifact@v4
        with:
          name: trivy-template
          path: /tmp/avenirs-workflows/trivy-template
