name: "Publish Reports (Javadoc, Coverage, Security)"
description: "Publish the Javadoc, coverage, and security reports to GitHub Pages"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  publish_dir:
    description: "Directory to publish"
    required: true
  security_report_dir:
    description: "Directory of the Security Report (OWASP Dependency Check)"
    required: false
    default: "dependency-check-report"
  linting_report_dir:
    description: "Directory of the Linting Report (Java, JavaScript, TypeScript)"
    required: false
    default: "lint"
  jacoco_report_dir:
    description: "Directory of the JaCoCo Report (Java)"
    required: false
    default: "jacoco-report"
  page_title:
    description: "Page title to be displayed on the GitHub Pages"
    required: false
    default: "Avenirs Documentation"
  javadoc_dir:
    description: "Directory of the Javadoc Report"
    required: false
    default: "apidocs"
  loading_report_dir:
    description: "Directory of the Loading tests Report (Java, JavaScript, TypeScript)"
    required: false
    default: "loading"

runs:
  using: "composite"
  steps:
    - name: (DEBUG) Check GITHUB_TOKEN
      if: ${{ false }}
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "Error: GITHUB_TOKEN is not set."
          exit 1
        else
          echo "GITHUB_TOKEN is set."
          echo "Token snippet: ${{ inputs.github_token }}"
        fi
      shell: bash

    - name: Download GitHub Page Template
      uses: actions/download-artifact@v4
      with:
        name: gh-page-template
        path: gh-page-template

    - name: Copy index page
      run: |
        mkdir -p ${{ inputs.publish_dir }}/docs/assets/images
        cp ./gh-page-template/index.html ${{ inputs.publish_dir }}/docs/index.html
        cp ./gh-page-template/assets/images/avenirs-esr-logo_medium.jpg ${{ inputs.publish_dir }}/docs/assets/images/avenirs-esr-logo_medium.jpg
        cp ./gh-page-template/assets/images/favicon.ico ${{ inputs.publish_dir }}/docs/assets/images/favicon.ico
        echo "Index file copied."
      shell: bash

    - name: Modify GitHub Page Template
      uses: avenirs-esr/avenirs-workflows/.github/actions/update-gh-pages-template@main
      with:
        page_title: ${{ inputs.page_title }}
        publish_dir: ${{ inputs.publish_dir }}
        javadoc_dir: ${{ inputs.javadoc_dir }}
        jacoco_report_dir: ${{ inputs.jacoco_report_dir }}
        linting_report_dir: ${{ inputs.linting_report_dir }}
        security_report_dir: ${{ inputs.security_report_dir }}
        loading_report_dir: ${{ inputs.loading_report_dir }}

    - name: Copy Security Report (if exists)
      if: ${{ inputs.security_report_dir }}
      run: |
        if [ -d "${{ inputs.security_report_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/${{ inputs.security_report_dir }}
          cp -r ${{ inputs.security_report_dir }}/* ${{ inputs.publish_dir }}/docs/${{ inputs.security_report_dir }}/
          echo "Security report copied to GitHub Pages."
        else
          echo "No security report found. Skipping."
        fi
      shell: bash

    - name: Copy Linting Report (if exists)
      if: ${{ inputs.linting_report_dir }}
      run: |
        if [ -d "${{ inputs.linting_report_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/${{ inputs.linting_report_dir }}
          cp -r ${{ inputs.linting_report_dir }}/* ${{ inputs.publish_dir }}/docs/${{ inputs.linting_report_dir }}/
          echo "Linting report copied to GitHub Pages."
        else
          echo "No linting report found. Skipping."
        fi
      shell: bash

    - name: Copy JaCoCo Report (if exists)
      if: ${{ inputs.jacoco_report_dir }}
      run: |
        if [ -d "jacoco-report" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/${{ inputs.jacoco_report_dir }}
          cp -r ${{ inputs.jacoco_report_dir }}/* ${{ inputs.publish_dir }}/docs/${{ inputs.jacoco_report_dir }}/
          echo "JaCoCo report copied to GitHub Pages."
        else
          echo "No JaCoCo report found. Skipping."
        fi
      shell: bash

    - name: Copy Javadoc (if exists)
      if: ${{ inputs.javadoc_dir }}
      run: |
        if [ -d "${{ inputs.javadoc_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/${{ inputs.javadoc_dir }}
          cp -r ${{ inputs.javadoc_dir }}/* ${{ inputs.publish_dir }}/docs/${{ inputs.javadoc_dir }}/
          echo "Javadoc copied to GitHub Pages."
        else
          echo "No Javadoc found. Skipping."
        fi
      shell: bash

    - name: Copy Load Tests Reports (if exists)
      if: ${{ inputs.loading_report_dir }}
      run: |
        if [ -d "${{ inputs.loading_report_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/${{ inputs.loading_report_dir }}
          cp -r ${{ inputs.loading_report_dir }}/* ${{ inputs.publish_dir }}/docs/${{ inputs.loading_report_dir }}/
          echo "Loading reports copied to GitHub Pages."
        else
          echo "No loading reports found. Skipping."
        fi
      shell: bash

    - name: Publish Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ inputs.publish_dir }}
