name: "Publish Reports (Javadoc, Coverage, Security)"
description: "Publish the Javadoc, coverage, and security reports to GitHub Pages"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  publish_dir:
    description: "Directory to publish"
    required: true
  security_report_dir:
    description: "Directory of the Security Report (OWASP Dependency Check)"
    required: false
    default: "dependency-check-report"
  linting_report_dir:
    description: "Directory of the Linting Report (Java, JavaScript, TypeScript)"
    required: false
    default: "lint"
  jacoco_report_dir:
    description: "Directory of the JaCoCo Report (Java)"
    required: false
    default: "jacoco-report"

runs:
  using: "composite"
  steps:
    - name: (DEBUG) Check GITHUB_TOKEN
      if: ${{ false }}
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "Error: GITHUB_TOKEN is not set."
          exit 1
        else
          echo "GITHUB_TOKEN is set."
          echo "Token snippet: ${{ inputs.github_token }}"
        fi
      shell: bash

    - name: Download GitHub Page Template
      uses: actions/download-artifact@v4
      with:
        name: gh-page-template
        path: gh-page-template

    - name: Copy index page
      run: |
        mkdir -p ${{ inputs.publish_dir }}/docs/assets/images
        cp /gh-page-template/index.html ${{ inputs.publish_dir }}/docs/index.html
        cp /gh-page-template/assets/images/avenirs-esr-logo_medium.jpg ${{ inputs.publish_dir }}/docs/assets/images/avenirs-esr-logo_medium.jpg
        cp /gh-page-template/assets/images/favicon.ico ${{ inputs.publish_dir }}/docs/assets/images/favicon.ico
        echo "Index file copied."
      shell: bash

    - name: Copy Security Report (if exists)
      if: ${{ inputs.security_report_dir }}
      run: |
        if [ -d "${{ inputs.security_report_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/security
          cp -r ${{ inputs.security_report_dir }}/* ${{ inputs.publish_dir }}/docs/security/
          echo "Security report copied to GitHub Pages."
        else
          echo "No security report found. Skipping."
        fi
      shell: bash

    - name: Copy Linting Report (if exists)
      if: ${{ inputs.linting_report_dir }}
      run: |
        if [ -d "${{ inputs.linting_report_dir }}" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/lint
          cp -r ${{ inputs.linting_report_dir }}/* ${{ inputs.publish_dir }}/docs/lint/
          echo "Linting report copied to GitHub Pages."
        else
          echo "No linting report found. Skipping."
        fi
      shell: bash

    - name: Copy JaCoCo Report (if exists)
      if: ${{ inputs.jacoco_report_dir }}
      run: |
        if [ -d "jacoco-report" ]; then
          mkdir -p ${{ inputs.publish_dir }}/docs/jacoco-report
          cp -r ${{ inputs.jacoco_report_dir }}/* ${{ inputs.publish_dir }}/docs/jacoco-report/
          echo "JaCoCo report copied to GitHub Pages."
        else
          echo "No JaCoCo report found. Skipping."
        fi
      shell: bash

    - name: Publish Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ inputs.publish_dir }}
