name: "Load tests"
description: "Executes load test with locust"
inputs:
  app_url:
    description: "Application url to test"
    required: true

  fixtures:
    description: "Fixtures sql file"
    required: true

  postgres_host:
    description: "Postgres host"
    required: false
    default: "localhost"

  postgres_port:
    description: "Postgres port"
    required: false
    default: "65432"

  postgres_user:
    description: "Postgres user"
    required: false
    default: $POSTGRES_USER

  postgres_db:
    description: "Postgres database"
    required: false
    default: "$POSTGRES_DB"

  locust_file:
    description: "Locust file name"
    required: false
    default: "locustfile.py"

  locust_report:
    description: "Locust report file"
    required: false
    default: "./target/site/locust_report.html"

  locust_csv_reports:
    description: "Locust csv reports base name"
    required: false
    default: "./target/site/locust_report"

  locust_duration:
      description: "Duration of the test"
      required: false
      default: "1m"

  locust_users:
      description: "Number of users for the load test"
      required: false
      default: "100"

  locust_ramp_rate:
      description: "User ramp rate"
      required: false
      default: "10"

runs:
  using: "composite"
  steps:
    - name: Load Test Data
      run: |
        echo "Loading test data..."
        psql -h ${{inputs.postgres_host}} -p ${{inputs.postgres_port}}  -U ${{inputs.postgres_user}} -d ${{inputs.postgres_db}} -f ${{ inputs.fixtures }}
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: python-cache-${{ runner.os }}-${{ hashFiles(inputs.locust_file) }}
        restore-keys: |
          python-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust
      shell: bash

    - name: Run Locust Load Test
      run: |
        locust -f ${{inputs.locust_file}} \
          --host=${{inputs.app_url}} \
          --headless \
          -u ${{inputs.locust_users}} \
          -r ${{inputs.locust_ramp_rate }} \
          --run-time ${{inputs.locust_duration}} \
          --html ${{inputs.locust_report}} \
          --csv ${{inputs.locust_csv_reports}}

      shell: bash

    - name: Upload Locust report
      uses: actions/upload-artifact@v4
      with:
        name: locust-report
        path: |
          ./target/site/locust_report.html
          ./target/site/locust_report_stats.csv
          ./target/site/locust_report_failures.csv


