name: Create GitHub App token
description: "Create a GitHub App token for the current repository owner."
inputs:
  app_id:
    description: "GitHub App ID (numeric)"
    required: true
  app_private_key:
    description: "GitHub App private key (PEM)"
    required: true
  owner:
    description: "Owner (user or org) of the installation"
    required: false
    default: ${{ github.repository_owner }}
outputs:
    app-token:
        description: "GitHub App token"
        value: ${{ steps.app-token.outputs.token }}
    app-slug:
      description: "GitHub App slug"
      value: ${{ steps.app-token.outputs.app-slug }}
runs:
  using: "composite"
  steps:
    - id: app-token
      name: 🔐 GitHub App token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}
        owner: ${{ inputs.owner }}
