name: "Deploy on Server"
description: "Deploy application on a remote server using SSH"

inputs:
  srv_base_path:
    required: true
    description: "Base path on the server where the application is located"
  srv_deploy_cmd:
    required: true
    description: "Command to deploy the application on the server (e.g., ./deploy.sh)"
  srv_update_deployment_cmd:
    required: true
    description: "Command to update deployment (e.g., ./update-deployment.sh)"
  jasypt_encryptor_password:
    required: true
    description: "Password for Jasypt encryption"
  java_version:
    required: true
    description: "Java version (e.g., 21.0.4-oracle)"
  maven_version:
    required: true
    description: "Maven version (e.g., 3.9.9)"
  conf_path:
    required: false
    description: "Configuration file path (directory) on the server"
  conf_file:
    required: false
    description: "Configuration file name"
  tag_name:
    required: false
    default: ""
    description: "Fallback tag if resolved_pairs is empty"
  resolved_pairs:
    required: false
    default: ""
    description: "Multiline repo=tag list (e.g. 'avenirs-portfolio-api=v1.0.0-qa\navenirs-cofolio-client=v1.0.1-qa')"

runs:
  using: "composite"
  steps:
    - name: 🛠️ Update config with logs
      if: ${{ inputs.tag_name != '' || inputs.resolved_pairs != '' }}
      shell: bash
      env:
        CONF_DIR: ${{ inputs.conf_path }}
        CONF_FILE: ${{ inputs.conf_file }}
        SRV_BASE_PATH: ${{ inputs.srv_base_path }}
        RESOLVED_PAIRS: ${{ inputs.resolved_pairs }}
        TAG_NAME: ${{ inputs.tag_name }}
      run: |
        set -euo pipefail
        if [ -z "${CONF_FILE:-}" ]; then
          echo "::warning::CONF_FILE not provided, skipping update."
          exit 0
        fi

        CONF_PATH="$CONF_FILE"
        if [ -n "${CONF_DIR:-}" ]; then
          CONF_PATH="$CONF_DIR/$CONF_FILE"
        fi

        if [ ! -f "$CONF_PATH" ]; then
          echo "::warning::Config file not found: $CONF_PATH — nothing to update."
          exit 0
        fi

        echo "::group::🧩 Process resolved_pairs"
        PAIRS_STR="$(printf %s "$RESOLVED_PAIRS")"
        if [ -z "$PAIRS_STR" ]; then
          echo "::warning::RESOLVED_PAIRS is empty. Skipping update."
          exit 0
        fi

        echo "➡️ Starting replacements for each repo=tag pair..."

        while IFS='=' read -r repo tag; do
          repo="${repo//$'\r'/}"
          tag="${tag//$'\r'/}"
          if [ -z "${repo:-}" ] || [ -z "${tag:-}" ]; then
            echo "⚠️  Skipping empty line or invalid pair: '$repo' = '$tag'"
            continue
          fi

          echo "--------------------------------------------------"
          echo "🔸 Processing: repo='$repo', tag='$tag'"

          esc_tag=$(printf '%s\n' "$tag" | sed 's/[\/&]/\\&/g')
          key="services/avenirs-portfolio/${repo}"
          echo "  ➜ Target key: $key"

          grep -E "^ *${key} *=" "$CONF_PATH" && echo "  (Found line to update)" || echo "  (Key not found, will not update)"

          sed -i -E "s|^([[:space:]]*)${key}([[:space:]]*)=([[:space:]]*).*$|\1${key} = ${esc_tag}|" "$CONF_PATH"

          if grep -qE "^ *${key} *= *${esc_tag}" "$CONF_PATH"; then
            echo "✅ Updated: ${key} = ${esc_tag}"
          elif grep -qE "^ *${key} *=" "$CONF_PATH"; then
            echo "⚠️  Found key but value unchanged (possible sed regex mismatch)"
          else
            echo "❌ Key not found: ${key}"
          fi
        done <<< "$RESOLVED_PAIRS"

        echo "🧾 Final content of $CONF_PATH (for debug):"
        echo "----------------------------------------"
        cat "$CONF_PATH" | sed 's/^/  /'
        echo "----------------------------------------"


    - name: 🚀 Run local deploy command
      shell: bash
      env:
        SRV_BASE_PATH: ${{ inputs.srv_base_path }}
        SRV_DEPLOY_CMD: ${{ inputs.srv_deploy_cmd }}
        SRV_UPDATE_DEPLOYMENT_CMD: ${{ inputs.srv_update_deployment_cmd }}
        JAVA_VERSION: ${{ inputs.java_version }}
        MAVEN_VERSION: ${{ inputs.maven_version }}
        JASYPT: ${{ inputs.jasypt_encryptor_password }}
      run: |
        export SDKMAN_DIR="$HOME/.sdkman"
        [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && . "$SDKMAN_DIR/bin/sdkman-init.sh"
        export JAVA_HOME="$(sdk home java "$JAVA_VERSION")"
        export M2_HOME="$(sdk home maven "$MAVEN_VERSION")"
        export PATH="$JAVA_HOME/bin:$M2_HOME/bin:$PATH"
        export JASYPT_ENCRYPTOR_PASSWORD="$JASYPT"

        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

        cd "$SRV_BASE_PATH" || { echo "::error::Base path not found"; exit 10; }
        "$SRV_UPDATE_DEPLOYMENT_CMD" || { echo "::error::Update deployment command failed"; exit 20; }
        "$SRV_DEPLOY_CMD" || { echo "::error::Deploy command failed"; exit 30; }
        echo "✅ Deployment finished."
