name: "Deploy on Server"
description: "Deploy application on a remote server using SSH"

inputs:
  srv_base_path:
    description: "Base path on the server where the application is located"
    required: true
  srv_deploy_cmd:
    description: "Command to deploy the application on the server (e.g., ./deploy.sh)"
    required: true
  jasypt_encryptor_password:
    description: "Password for Jasypt encryption"
    required: true
  java_version:
    description: "Java version to use on the server (e.g., 21.0.4-oracle)"
    required: true
  maven_version:
    description: "Maven version to use on the server (e.g., 3.9.9)"
    required: true
  conf_path:
    description: "Path to the configuration file on the server (if needed)"
    required: false
  conf_file:
    description: "Configuration file name (if needed)"
    required: false
  tag_name:
    description: "Tag name for the deployment (if needed)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: 🛠️ Update config (optional tag)
      run: |
        TAG_NAME='${{ inputs.tag_name }}'
        CONF_DIR='${{ inputs.conf_path }}'
        CONF_FILE='${{ inputs.conf_file }}'
        SRV_BASE_PATH='${{ inputs.srv_base_path }}'

        [ -n "$TAG_NAME" ] || exit 0

        cd "$SRV_BASE_PATH"
        if [ -n "$CONF_FILE" ]; then
          CONF_PATH="$CONF_FILE"
          [ -n "$CONF_DIR" ] && CONF_PATH="$CONF_DIR/$CONF_FILE"
          if [ -f "$CONF_PATH" ]; then
           esc_tag=$(printf '%s\n' "$TAG_NAME" | sed 's/[\/&]/\\&/g')
           keys=(
             'services/avenirs-portfolio/avenirs-cofolio-client'
             'services/avenirs-portfolio/avenirs-portfolio-api'
           )
           for k in "${keys[@]}"; do
             sed -i -E "s|^([[:space:]]*)${k}([[:space:]]*)=([[:space:]]*).*$|\1${k} = ${esc_tag}|" "$CONF_PATH"
           done
           echo "✔ Conf mise à jour :"
           for k in "${keys[@]}"; do
             grep -E "^ *${k} *=" "$CONF_PATH" || true
           done
          else
           echo "::warning::Fichier de conf introuvable: $CONF_PATH"
          fi
        fi
      shell: bash

    - name: 🚀 Run local deploy command
      run: |
        SRV_BASE_PATH='${{ inputs.srv_base_path }}'
        SRV_DEPLOY_CMD='${{ inputs.srv_deploy_cmd }}'
        JAVA_VERSION='${{ inputs.java_version }}'
        MAVEN_VERSION='${{ inputs.maven_version }}'
        JASYPT='${{ inputs.jasypt_encryptor_password }}'

        export SDKMAN_DIR="$HOME/.sdkman"
        [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && . "$SDKMAN_DIR/bin/sdkman-init.sh"
        export JAVA_HOME="$(sdk home java "$JAVA_VERSION")"
        export M2_HOME="$(sdk home maven "$MAVEN_VERSION")"
        export PATH="$JAVA_HOME/bin:$M2_HOME/bin:$PATH"
        export JASYPT_ENCRYPTOR_PASSWORD="$JASYPT"

        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

        cd "$SRV_BASE_PATH" || { echo "::error::Base path not found"; exit 10; }

        echo "Running: $SRV_DEPLOY_CMD"
        "$SRV_DEPLOY_CMD"

        echo "✅ Deployment finished."
      shell: bash
