name: Only Develop to Main PR Validation
on:
  workflow_call:

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: ⛔ Fail if PR is not from develop
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "::error::Pull requests to 'main' are only allowed from 'develop'"
            exit 1
          fi
