name: "Qualif Deployment Workflow"

on:
  workflow_call:
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_TOKEN:
        required: true
      SRV_BASE_PATH:
        required: true
      SRV_DEPLOY_CMD:
        required: true
      SRV_UPDATE_DEPLOYMENT_CMD:
        required: true
      JASYPT_ENCRYPTOR_PASSWORD:
        required: true
      EMPTY_DATASET_ACCESS_TOKEN:
        required: true
      ADMIN_TOKEN:
        required: true
      BEARER_TOKEN:
        required: true
      ROCKETCHAT_API_URL:
        required: true
      ROCKETCHAT_TOKEN:
        required: true
      ROCKETCHAT_USER_ID:
        required: true
      WIKI_APP_ID:
        required: true
      WIKI_APP_TOKEN:
        required: true
    outputs:
      should_run:
        description: "true if at least one matching User Story is found in In Review"
        value: ${{ jobs.check.outputs.should_run }}

permissions:
  issues: read
  contents: read
  repository-projects: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.get_us.outputs.should_run }}
      count: ${{ steps.get_us.outputs.count }}
      issues_json: ${{ steps.get_us.outputs.issues_json }}

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 🔍 Get US in In Review
        id: get_us
        uses: avenirs-esr/avenirs-workflows/.github/actions/get-issues-in-column@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          target_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}
          issue_type: ${{ vars.US_ISSUE_TYPE }}
          org: ${{ vars.ORG }}

  e2e:
    name: "Run E2E Tests"
    needs: [ check ]
    if: ${{ needs.check.outputs.should_run == 'true' }}
    runs-on:
      group: Default
      labels:
        - self-hosted
        - ${{ vars.SRV_DEV_LABEL}}
    permissions:
      contents: read

    outputs:
      report_path: ${{ steps.report_meta.outputs.report_path }}
      report_url: ${{ steps.report_meta.outputs.report_url }}

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 🧭 Build report metadata
        id: report_meta
        shell: bash
        run: |
          REPORT_PATH="e2e-reports/${GITHUB_RUN_ID}"
          REPORT_URL="https://avenirs-esr.github.io/avenirs-workflows/${REPORT_PATH}/"

          echo "report_path=${REPORT_PATH}" >> "$GITHUB_OUTPUT"
          echo "report_url=${REPORT_URL}" >> "$GITHUB_OUTPUT"

      - name: ♻️ Reset and seed DEV dataset
        uses: avenirs-esr/avenirs-workflows/.github/actions/reset-and-seed-dataset@main
        with:
          seeding_endpoint_path: ${{ vars.SEEDING_ENDPOINT_URL }}
          admin_token: ${{ secrets.ADMIN_TOKEN }}
          bearer_token: ${{ secrets.BEARER_TOKEN }}

      - name: 🎭 Run E2E Tests
        id: e2e
        uses: avenirs-esr/avenirs-workflows/.github/actions/run-e2e-tests@main
        with:
          base_url: ${{ vars.DEV_COFOLIO_URL }}
          run_local_preview: "false"
          enable_msw: "false"
          upload_report: "true"
          chrome_only: "false"
          review_mode: "true"
          need_to_checkout: "true"
          token: ${{ steps.app.outputs.app-token }}
          empty_dataset_access_token: ${{ secrets.EMPTY_DATASET_ACCESS_TOKEN }}

  publish-report:
    name: "Publish Playwright report to central Pages"
    needs: [ check, e2e ]
    if: ${{ always() && (needs.e2e.result == 'failure') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      report_url: ${{ needs.e2e.outputs.report_url }}

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.WIKI_APP_ID }}
          app_private_key: ${{ secrets.WIKI_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 📥 Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: 🚀 Deploy report to avenirs-workflows gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ steps.app.outputs.app-token }}
          external_repository: avenirs-esr/avenirs-workflows
          publish_branch: gh-pages
          publish_dir: playwright-report
          destination_dir: ${{ needs.e2e.outputs.report_path }}
          keep_files: true

  deploy:
    needs: [check, e2e]
    if: ${{ success() && needs.check.outputs.should_run == 'true' }}
    runs-on:
      group: Default
      labels:
        - self-hosted
        - ${{ vars.SRV_QUALIF_LABEL }}
    permissions:
      contents: read

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🚀 Deploy application on remote server
        uses: avenirs-esr/avenirs-workflows/.github/actions/deploy-on-server@main
        with:
          srv_base_path: ${{ secrets.SRV_BASE_PATH }}
          srv_deploy_cmd: ${{ secrets.SRV_DEPLOY_CMD }}
          srv_update_deployment_cmd: ${{ secrets.SRV_UPDATE_DEPLOYMENT_CMD }}
          jasypt_encryptor_password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
          java_version: ${{ vars.JAVA_VERSION }}
          maven_version: ${{ vars.MAVEN_VERSION }}

  finalize:
    needs: [check, e2e, deploy]
    if: ${{ always() && needs.check.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 💬 Comment all US in In Review (tests failed)
        if: ${{ needs.e2e.result != 'success' || needs.deploy.result != 'success' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/group-issues-commentary@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          from_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}
          body: |
            ❌ Nightly workflow failed. Deployment cancelled.
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          org: ${{ vars.ORG }}
          us_issue_type: ${{ vars.US_ISSUE_TYPE }}

      - name: 🧭 Move US to Recette in Project
        if: ${{ needs.e2e.result == 'success' && needs.deploy.result == 'success' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/group-issues-status-update@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          from_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}
          target_status_name: ${{ vars.RECETTE_STATUS_NAME }}
          org: ${{ vars.ORG }}
          us_issue_type: ${{ vars.US_ISSUE_TYPE }}

      - name: Build message
        if: ${{ needs.e2e.result == 'success' && needs.deploy.result == 'success' }}
        id: build_message
        uses: avenirs-esr/avenirs-workflows/.github/actions/build-us-column-message@main
        with:
          issues_json: ${{ needs.check.outputs.issues_json }}
          count: ${{ needs.check.outputs.count }}
          header_message: "🧪 Nouvelle(s) US déployée(s) sur qualif :"
          empty_message: "ℹ️ Aucune User Story déployée sur qualif."

      - name: 🔍 Get US in In Review
        id: get_us_in_recette
        uses: avenirs-esr/avenirs-workflows/.github/actions/get-issues-in-column@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          target_status_name: ${{ vars.IN_RECETTE_STATUS_NAME }}
          issue_type: ${{ vars.US_ISSUE_TYPE }}
          org: ${{ vars.ORG }}
          sprint: "@current"

      - name: 🚀 Notify Rocket.Chat
        if: ${{ needs.e2e.result == 'success' && needs.deploy.result == 'success' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/rocket-chat-notify@main
        with:
          api-url: ${{ secrets.ROCKETCHAT_API_URL }}
          auth-token: ${{ secrets.ROCKETCHAT_TOKEN }}
          user-id: ${{ secrets.ROCKETCHAT_USER_ID }}
          channel: '#Avenirs_fonctionnel'
          message: |
            🚀 [BOT] Déploiement sur qualif OK

            ${{ steps.build_message.outputs.message }}

            Pour info, il y a ${{ steps.get_us_in_recette.outputs.count }} dans la colonne Recette ( ${{ vars.COFOLIO_PROJECT_URL }} ).

  notify:
    name: 🚀 Notify Rocket.Chat
    needs: [check, e2e, publish-report, deploy]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.check.outputs.should_run == 'true' }}

    steps:
      - name: 🚀 Send Rocket.Chat notification
        uses: avenirs-esr/avenirs-workflows/.github/actions/rocket-chat-notify@main
        with:
          api-url: ${{ secrets.ROCKETCHAT_API_URL }}
          auth-token: ${{ secrets.ROCKETCHAT_TOKEN }}
          user-id: ${{ secrets.ROCKETCHAT_USER_ID }}
          channel: ${{ vars.ROCKET_CHAT_NOTIFICATION_CANAL }}
          message: |
            ${{
              needs.e2e.result == 'success' && needs.deploy.result == 'success' &&
              '🚀 [BOT] Déploiement réussi sur qualif' ||

              needs.e2e.result == 'failure' &&
              '❌ [BOT] Tests E2E échoués. Déploiement annulé.' ||

              needs.deploy.result == 'cancelled' &&
              '⚠️ [BOT] Déploiement annulé sur qualif' ||

              '❌ [BOT] Déploiement échoué sur qualif'
            }}
            ${{
              !(needs.e2e.result == 'success' && needs.deploy.result == 'success') &&
              format('🔎 Run: {0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id) ||
              ''
            }}
            ${{
              (needs.e2e.result == 'failure' && needs.publish-report.outputs.report_url != '') &&
              format('📊 Rapport Playwright : {0}', needs.publish-report.outputs.report_url) ||
              ''
            }}
