name: "Qualif Deployment Workflow"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      GH_APP_ID:
        required: true
      GH_APP_TOKEN:
        required: true
      SRV_BASE_PATH:
        required: true
      SRV_DEPLOY_CMD:
        required: true
      SRV_UPDATE_DEPLOYMENT_CMD:
        required: true
      JASYPT_ENCRYPTOR_PASSWORD:
        required: true
      EMPTY_DATASET_ACCESS_TOKEN:
        required: true
      ADMIN_TOKEN:
        required: true
      BEARER_TOKEN:
        required: true
    outputs:
      should_run:
        description: "true if parent is User Story AND all its sub-issues are closed"
        value: ${{ jobs.check.outputs.should_run }}

permissions:
  issues: read
  contents: read
  repository-projects: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_us.outputs.should_run }}

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 🔍 Search US In Review
        id: check_us
        uses: avenirs-esr/avenirs-workflows/.github/actions/check-us-in-column@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          target_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}

      - name: ♻️ Reset and seed DEV dataset
        if: ${{ steps.check_us.outputs.should_run == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/reset-and-seed-dataset@fix/reset-and-seeding
        with:
          seeding_endpoint_path: ${{ vars.SEEDING_ENDPOINT_URL }}
          admin_token: ${{ secrets.ADMIN_TOKEN }}
          bearer_token: ${{ secrets.BEARER_TOKEN }}

      - name: 🎭 Run E2E Tests
        if: ${{ steps.check_us.outputs.should_run == 'true' }}
        id: e2e
        uses: avenirs-esr/avenirs-workflows/.github/actions/run-e2e-tests@main
        with:
          base_url: ${{ vars.DEV_COFOLIO_URL }}
          run_local_preview: "false"
          enable_msw: "false"
          upload_report: "false"
          chrome_only: "false"
          review_mode: "true"
          need_to_checkout: "true"
          token: ${{ steps.app.outputs.app-token }}
          empty_dataset_access_token: ${{ secrets.EMPTY_DATASET_ACCESS_TOKEN }}

  deploy:
    needs: check
    if: ${{ success() && needs.check.outputs.should_run == 'true' }}
    runs-on:
      group: Default
      labels:
        - self-hosted
        - ${{ vars.SRV_QUALIF_LABEL }}
    permissions:
      contents: read

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🚀 Deploy application on remote server
        uses: avenirs-esr/avenirs-workflows/.github/actions/deploy-on-server@main
        with:
          srv_base_path: ${{ secrets.SRV_BASE_PATH }}
          srv_deploy_cmd: ${{ secrets.SRV_DEPLOY_CMD }}
          srv_update_deployment_cmd: ${{ secrets.SRV_UPDATE_DEPLOYMENT_CMD }}
          jasypt_encryptor_password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
          java_version: ${{ vars.JAVA_VERSION }}
          maven_version: ${{ vars.MAVEN_VERSION }}

  finalize:
    needs: [check, deploy]
    if: ${{ always() && needs.check.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read

    steps:
      - name: 🔐 Create GitHub App token
        id: app
        uses: avenirs-esr/avenirs-workflows/.github/actions/github-app-token@main
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_TOKEN }}
          owner: ${{ vars.ORG }}

      - name: 💬 Comment all US in In Review (tests failed)
        if: ${{ needs.check.result != 'success' || needs.deploy.result != 'success' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/group-issues-commentary@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          from_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}
          body: |
            ❌ Nightly workflow failed. Deployment cancelled.
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: 🧭 Move US to Recette in Project
        if: ${{ needs.check.result == 'success' && needs.deploy.result == 'success' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/group-issues-status-update@main
        with:
          token: ${{ steps.app.outputs.app-token }}
          project_number: ${{ vars.COFOLIO_PROJECT_NUMBER }}
          from_status_name: ${{ vars.IN_REVIEW_STATUS_NAME }}
          target_status_name: ${{ vars.RECETTE_STATUS_NAME }}
