name: "Stop Spring boot app"
description: "Stop a Spring boot application"
inputs:
    app_url:
      description: "Application url"
      required: true
runs:
  using: "composite"

  steps:
    - name: Stop application
      run: |
        if [ -f spring-boot.pid ]; then
          kill $(cat spring-boot.pid) && rm spring-boot.pid
        else
          echo "No PID file found. Application might not be running."
        fi
      shell: bash